<a href="https://colab.research.google.com/github/ramrajv/Ramraj_Prayag_Kaggle/blob/main/Test/TelecomChurn_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Load libraries
import numpy as np
import pandas as pd

import datetime as dt

import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import seaborn as sns
sns.set(style="ticks")
%matplotlib inline

from scipy.stats import norm
from scipy import stats

import sklearn
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings("ignore")

In [4]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [7]:
drop_cols = train.columns[train.isna().sum()/train.shape[0]>0.5]

In [8]:
drop_cols

Index(['date_of_last_rech_data_6', 'date_of_last_rech_data_7',
       'date_of_last_rech_data_8', 'total_rech_data_6', 'total_rech_data_7',
       'total_rech_data_8', 'max_rech_data_6', 'max_rech_data_7',
       'max_rech_data_8', 'count_rech_2g_6', 'count_rech_2g_7',
       'count_rech_2g_8', 'count_rech_3g_6', 'count_rech_3g_7',
       'count_rech_3g_8', 'av_rech_amt_data_6', 'av_rech_amt_data_7',
       'av_rech_amt_data_8', 'arpu_3g_6', 'arpu_3g_7', 'arpu_3g_8',
       'arpu_2g_6', 'arpu_2g_7', 'arpu_2g_8', 'night_pck_user_6',
       'night_pck_user_7', 'night_pck_user_8', 'fb_user_6', 'fb_user_7',
       'fb_user_8'],
      dtype='object')

In [9]:
train.drop(drop_cols, axis = 1, inplace = True)

In [10]:
train.shape

(69999, 142)

In [13]:
train.columns[train.nunique()<10]

Index(['circle_id', 'loc_og_t2o_mou', 'std_og_t2o_mou', 'loc_ic_t2o_mou',
       'last_date_of_month_6', 'last_date_of_month_7', 'last_date_of_month_8',
       'std_og_t2c_mou_6', 'std_og_t2c_mou_7', 'std_og_t2c_mou_8',
       'std_ic_t2o_mou_6', 'std_ic_t2o_mou_7', 'std_ic_t2o_mou_8',
       'monthly_2g_6', 'monthly_2g_7', 'monthly_2g_8', 'churn_probability'],
      dtype='object')

In [14]:
train.columns[
              (train.nunique()>=10)&
              (train.nunique()<20)
              ]

Index(['monthly_3g_6', 'monthly_3g_7', 'monthly_3g_8'], dtype='object')

In [16]:
train.columns[
              (train.nunique()>=20)&
              (train.nunique()<32)
              ]

Index(['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8',
       'sachet_2g_6', 'sachet_3g_6', 'sachet_3g_7', 'sachet_3g_8'],
      dtype='object')

In [17]:
train.columns[
              (train.nunique()>=32)&
              (train.nunique()<100)
              ]

Index(['spl_ic_mou_6', 'spl_ic_mou_8', 'total_rech_num_6', 'total_rech_num_7',
       'total_rech_num_8', 'sachet_2g_7', 'sachet_2g_8'],
      dtype='object')

In [18]:
drop_cols = train.columns[train.nunique()==1]

In [19]:
train.drop(drop_cols, axis = 1, inplace = True)

In [21]:
train.columns[train.nunique()<20]

Index(['monthly_2g_6', 'monthly_2g_7', 'monthly_2g_8', 'monthly_3g_6',
       'monthly_3g_7', 'monthly_3g_8', 'churn_probability'],
      dtype='object')

In [22]:
X = train.drop('churn_probability',axis = 1)

In [23]:
X.columns[X.nunique()<20]

Index(['monthly_2g_6', 'monthly_2g_7', 'monthly_2g_8', 'monthly_3g_6',
       'monthly_3g_7', 'monthly_3g_8'],
      dtype='object')

In [24]:
X.columns[
              (X.nunique()>=20)&
              (X.nunique()<32)
              ]

Index(['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8',
       'sachet_2g_6', 'sachet_3g_6', 'sachet_3g_7', 'sachet_3g_8'],
      dtype='object')

In [25]:
X['monthly_2g_6'].unique()

array([0, 1, 2, 3, 4])

In [26]:
X['monthly_2g_7'].unique()

array([0, 1, 2, 4, 3, 5])

In [27]:
X['monthly_2g_8'].unique()

array([0, 1, 2, 4, 3, 5])

In [28]:
X['monthly_3g_6'].unique()

array([0, 1, 2, 4, 3, 5, 6, 8, 7, 9])

In [29]:
X['monthly_3g_7'].unique()

array([ 0,  1,  2,  3,  5,  4,  8,  6,  7, 16, 14,  9, 10])

In [30]:
X['monthly_3g_8'].unique()

array([ 0,  1,  2,  3,  4,  8,  5,  6,  9,  7, 16, 10])

In [31]:
cols = ['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8',
       'sachet_2g_6', 'sachet_3g_6', 'sachet_3g_7', 'sachet_3g_8']
for col in cols:
  print(col,':',X[col].unique())

date_of_last_rech_6 : ['6/22/2014' '6/12/2014' '6/11/2014' '6/15/2014' '6/25/2014' '6/30/2014'
 '6/29/2014' '6/20/2014' '6/28/2014' '6/27/2014' '6/26/2014' '6/19/2014'
 '6/23/2014' '6/24/2014' '6/14/2014' nan '6/5/2014' '6/8/2014' '6/6/2014'
 '6/16/2014' '6/13/2014' '6/18/2014' '6/21/2014' '6/17/2014' '6/10/2014'
 '6/7/2014' '6/2/2014' '6/1/2014' '6/3/2014' '6/9/2014' '6/4/2014']
date_of_last_rech_7 : ['7/10/2014' '7/22/2014' '7/21/2014' '7/26/2014' '7/27/2014' '7/19/2014'
 '7/30/2014' '7/16/2014' '7/31/2014' '7/20/2014' '7/25/2014' '7/29/2014'
 '7/28/2014' nan '7/7/2014' '7/18/2014' '7/13/2014' '7/17/2014'
 '7/12/2014' '7/24/2014' '7/15/2014' '7/1/2014' '7/23/2014' '7/9/2014'
 '7/8/2014' '7/14/2014' '7/5/2014' '7/4/2014' '7/11/2014' '7/6/2014'
 '7/2/2014' '7/3/2014']
date_of_last_rech_8 : ['8/24/2014' '8/26/2014' '8/25/2014' '8/30/2014' '8/28/2014' '8/19/2014'
 '8/5/2014' '8/27/2014' '8/16/2014' '8/21/2014' '8/22/2014' '8/23/2014'
 nan '8/15/2014' '8/31/2014' '8/12/2014' '8/10/2014' '